name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Verify secrets exist
      - name: Check secrets
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "::error::GH_TOKEN is not set"
            exit 1
          else
            echo "✓ GH_TOKEN is set"
          fi
          if [ -z "${{ secrets.NOTIFICATION_EMAIL }}" ]; then
            echo "::error::NOTIFICATION_EMAIL is not set"
            exit 1
          else
            echo "✓ NOTIFICATION_EMAIL is set"
          fi

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      # Fix platform issue
      - name: Update bundle platforms
        run: |
          bundle lock --add-platform x86_64-linux
          bundle install

      - name: Create config.js
        run: |
          mkdir -p _site/assets/js
          cat > _site/assets/js/config.js << 'EOL'
          // GitHub token injected by GitHub Actions
          window.GITHUB_TOKEN = '${{ secrets.GH_TOKEN }}';
          window.NOTIFICATION_EMAIL = '${{ secrets.NOTIFICATION_EMAIL }}';
          console.log('Config loaded, token available:', !!window.GITHUB_TOKEN);
          EOL

          echo "Content of config.js (without token):"
          cat _site/assets/js/config.js | sed 's/window.GITHUB_TOKEN.*/window.GITHUB_TOKEN = [REDACTED];/'
          chmod 644 _site/assets/js/config.js

      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
          JEKYLL_PAT: ${{ secrets.GH_TOKEN }}

      - name: Verify build output
        run: |
          if [ ! -d "_site" ]; then
            echo "::error::_site directory not created"
            exit 1
          fi
          if [ ! -f "_site/assets/js/config.js" ]; then
            echo "::error::config.js not in build output"
            exit 1
          fi
          echo "✓ Build output verified"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true